name: daily_planner
description: A productivity app with task management, focus mode, app blocking, and assistant features.

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core and State Management - UPDATED TO STABLE RIVERPOD 2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: 0.21.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Networking
  http: ^1.2.0

  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.1
  percent_indicator: ^4.2.3
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.3.0
  flutter_launcher_icons: ^0.14.4
  lottie: ^2.7.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  flutter_local_notifications: ^17.0.0

  # Backend - UPDATED TO LATEST VERSION
  supabase_flutter: ^2.9.1
  timezone: ^0.9.2

  # ================================
  # AUTHENTICATION & OAUTH
  # ================================

  # Google Sign-In - FOR OAUTH IMPLEMENTATION
  google_sign_in: ^6.2.1

  # Apple Sign-In - FOR iOS OAUTH
  sign_in_with_apple: ^6.1.1

  # Firebase Auth (Optional - for additional OAuth providers)
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1

  # ================================
  # APP BLOCKER DEPENDENCIES
  # ================================

  # Device Apps - Get installed apps list
  device_apps: ^2.2.0

  # App Usage Monitoring - RE-ENABLED WITH FALLBACK
  app_usage: ^4.0.1


  # Background Service - For app monitoring
  flutter_background_service: ^5.0.5

  # Permissions - Handle Android permissions
  permission_handler: ^11.2.0

  # Shared Preferences - Local settings storage
  shared_preferences: ^2.2.2

  # ================================
  # PLATFORM SERVICES
  # ================================

  # Android Intents
  android_intent_plus: ^4.0.3

  # URL Launcher
  url_launcher: ^6.2.4

  # Package Info - Get app version and details
  package_info_plus: ^8.0.0

  # Device Info - Get device details
  device_info_plus: ^10.1.0

  # ================================
  # UTILITIES & HELPERS
  # ================================

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # Cryptography
  crypto: ^3.0.3

  # Connectivity - Check internet status
  connectivity_plus: ^6.0.3

  # Wakelock - Keep screen awake during focus
  wakelock_plus: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # UNCOMMENTED ASSETS - You can create these directories as needed
  assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  #   - assets/lottie/
      - .env

  # UNCOMMENTED FONTS - You can add font files as needed
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

# ================================
# FLUTTER CONFIGURATION
# ================================

# Enable null safety
analyzer:
  enable-experiment:
    - non-nullable
